### ISSUE TITLE
Can't get episodes that have non numerical "number" (Was: Can't get re:zero)

### ISSUE THREAD

**Issue by xXxBobDolexXx** [Godzil/crunchyroll.js#5]
Every other title I have tried has started to download like normal except Re:Zero, it just hangs there and does nothing. This is the command I am using

crunchy -u email -p password http://www.crunchyroll.com/rezero-starting-life-in-another-world-

**Comment by Jfigs101** [comment]
You should try to use the -s flag, like so, '-s 1', without the single quotes. This worked for me when I was trying to download one piece.

**Comment by xXxBobDolexXx** [comment]
That seems to have done it, from the looks of it it has skipped the 1A and 1B episodes but I can manually grab those I'm sure. Thanks!

**Comment by Godzil** [comment]
That's true that episodes like 1A/1B or X.Y are not treated correctly with the current code. I have a quick fix for that and will push it ASAP. Probably tonight (GMT timezone)

**Comment by Jfigs101** [comment]
How would I update crunchy Street you push your fix?

**Comment by xXxBobDolexXx** [comment]
It's just a guess but it's likely the same command used to originally install the npm module

**Comment by Godzil** [comment]
I've updated the code here on github and the NPM package, a

npm instal -g crunchy

should work to update it!

See: https://docs.npmjs.com/getting-started/updating-global-packages

Please tell me if something goes wrong on your side

1.1.9 add:
 - Should correctly handle 10.5 or 1A episode numbers
 - Change characters in series name that are not allowed in filename (or could cause issues, like slash ( / ) or single quote ( ' )
 - Prevent overwrite of existing files (usefull when different season report the same number)
 - If an error during episode metadata scraping, it will set to Season 0, episode 0 (look at the logs!)
 - If an episode is not available yet, it will be skipped

These changes are part of the upcomming 1.2 version, but are not in the final form, that why the version is not bumped.

**Comment by xXxBobDolexXx** [comment]
For the parameters, -s helps with some series that cannot otherwise be downloaded, I had to add "-s 1" to get re:zero to download at all, otherwise it just sits there doing nothing. The ones I use are

-o, -u, -p, and -s

**Comment by Godzil** [comment]
If there is any episode that make it fail please report it.

If you get any errors on mkvmerge run the command by hand and check the result. Some subtitles have errors that trigger a warning in mkvmerge

**Comment by xXxBobDolexXx** [comment]
No errors on any of the episodes, and the 1x episodes download well now too. The only current issue is that with re:zero, and one piece according to Jfigs101, is that when you use a command like this:

    crunchy -u email -p password -o d:/anime http://www.crunchyroll.com/rezero-starting-life-in-another-world-
![no s](https://cloud.githubusercontent.com/assets/13506674/18386416/807b5bce-7671-11e6-95da-a162eacd1652.JPG)


The command prompt window will go to the next line, but not display any more text after, and will not start the dodwnload

however when using this command:

    crunchy -u email -p password -o d:/anime -s 1 http://www.crunchyroll.com/rezero-starting-life-in-another-world-
![yes s](https://cloud.githubusercontent.com/assets/13506674/18386417/80809c56-7671-11e6-8e34-f5ca2db6e025.JPG)

The download then starts without issue,

**Comment by Godzil** [comment]
Hum I think the error is elsewhere, probably an incompatibility with Windows on the name. I wonder is Windows accept a ":" in the file name, I doubt it in fact. I will make a chan
ge for that.

**Comment by Jfigs101** [comment]
I would love to test, but I don't really have another anime I would like to download. Any suggestions? Also I would like to keep the -e, -s flags.

**Comment by xXxBobDolexXx** [comment]
Confirming that "-s 1" has not been needed for re:zero after 1.1.10.

**Comment by xXxBobDolexXx** [comment]
Also I have a question. A little off topic, but how difficult would multithread downloading be to add?

**Comment by xXxBobDolexXx** [comment]
An episode in Naruto failed:

    Error: Command failed: "C:\Users\xXxRobertDolexXx\AppData\Roaming\npm\node_modules\crunchy\bin\rtmpdump.exe" -r "rtmpe://cp150757.edgefcs.net/ondemand/?auth=daEdRbYaXdMaXbIdgdAbPcmdFbvaPbTbOcm-bx16yB-dHa-oBDwutPAGvy&aifp=0009&slist=c17/s/ve488694/v2/video.mp4" -y "mp4:c17/s/ve488694/v2/video.mp4" -W "http://www.crunchyroll.com/swf/StandardVideoPlayer.swf" -o "d:\anime\Naruto\Naruto - s01e06 - [CrunchyRoll].mp4"
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
WARNING: HandShake: Type mismatch: client sent 6, server answered 8
INFO: Connected...
ERROR: RTMP_ReadPacket, failed to read RTMP packet body. len: 9976089

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)




Not shippuden, original series. Starting the download again didnt produce the error

**Comment by Godzil** [comment]
That's an issue with rtpmdump that happen lately. The only thing that crunchy could do is to do a retry if rtmpdump fail.

For multiprocessing I would not recommend to hammer CR servers to download multiples episodes at the same time, they may enforce their conditions, or ban account that abuse their system.
That could be done, but either I would not recommend to do, nor I would implement that into crunchy. (and you will anyway be limited by your bandwidth so not sure if it's really interesting)

**Comment by Godzil** [comment]
(Closing because OP problem is solved, please create a new issue for bug/enhancement/question :-)
