### ISSUE TITLE
Will only download 1080p Regardless of setting on CR.

### ISSUE THREAD

**Issue by Jimm1432** [Godzil/crunchyroll.js#58]
as title, I've set my video setting to 720p on CR but crunchy Only downloads 1080p files.

Can I manually set the resolution in my batch file?

**Comment by Godzil** [comment]
That is not something I do have control at the moment in Crunchy.. I’ve also spotted that I always get the 1080 flux, and haven’t found a way to select another one. There is (still) a bit of mistery on how they select that, it is maybe cookie based so your configuration is browser based?

Hmmmm I should look at that

**Comment by Jimm1432** [comment]
what have you done and how do I change res?
