### ISSUE TITLE
Specific episode failing to download

### ISSUE THREAD

**Issue by xXxBobDolexXx** [Godzil/crunchyroll.js#6]
Command being run is:
"crunchy -u email@gmail.com -p password -o d:/anime -v 6 http://www.crunchyroll.com/naruto"
Only episode that has an issue is s07e164, to my knowledge the rest is working fine. Deleted a few episodes and tested with the 3 previous episodes to make sure that downloading itself was working and it is.

    Fetching Naruto - s07e164 - [CrunchyRoll]
    Experimental FFMPEG, MAY FAIL!!!
    Error: Command failed:     "C:\Users\username\AppData\Roaming\npm\node_modules\crunchy\bin\ffmpeg.exe" -i "" -c     copy -bsf:a aac_adtstoasc "d:\anime\Naruto\Naruto - s07e164 - [CrunchyRoll].mp4"
    ffmpeg version N-81328-gceab04f Copyright (c) 2000-2016 the FFmpeg developers
      built with gcc 5.4.0 (GCC)
      configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-dxva2 --enable-libmfx     --enable-nvenc --enable-avisynth --enable-bzlib --enable-libebur128 --enable-fontconfig --enable-    frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-    libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --    enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --    enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsnappy --enable-libsoxr --    enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc -    -enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-    libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-    zlib
      libavutil      55. 28.100 / 55. 28.100
      libavcodec     57. 51.102 / 57. 51.102
      libavformat    57. 46.101 / 57. 46.101
      libavdevice    57.  0.102 / 57.  0.102
      libavfilter     6. 51.100 /  6. 51.100
      libswscale      4.  1.100 /  4.  1.100
      libswresample   2.  1.100 /  2.  1.100
      libpostproc    54.  0.100 / 54.  0.100
    : No such file or directory

        at ChildProcess.exithandler (child_process.js:206:12)
        at emitTwo (events.js:106:13)
        at ChildProcess.emit (events.js:191:7)
        at maybeClose (internal/child_process.js:877:16)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by Godzil** [comment]
I can't test here, but there where some issues with changes on CR website, could you please try again with Version 1.1.11 ?
Also I had some issue with some download one day that solved themself the next day (and the episode was not working on the CR website at that moment) so maybe it was the issue there?

So please try again, and tell me how it's doing.

**Comment by xXxBobDolexXx** [comment]
Sorry missed the comment you had left. Restarted the download today and am confirming the issue is resolved. Thanks!
