### ISSUE TITLE
Receiving 'Ignoring...not release yet' in error

### ISSUE THREAD

**Issue by Jfigs101** [Godzil/crunchyroll.js#7]
I am attempting to download episode 10 of Mob Psycho 100, which is out, but I am receiving the error: 'Ignoring Mob Psycho 100 - s01e10 - [CrunchyRoll]: not released yet'

It became available on: 9/12 for premium users. 
It will become available on: 9/19 for free users. 

Is it possible it is looking at the free user date?

**Comment by Godzil** [comment]
I'm facing some issues on my side too, I have the impression that the login mechanisms is no longer working, I will have to check on that point. So if you download in more than 480p, be careful of what you get, if you get only some 480p-ish that mean that the login no longer work.

**Comment by Jfigs101** [comment]
I used crunchyroll.js to download and I received 480p quality. Looks like that other project I linked you a while back is also having login issues.

**Comment by Godzil** [comment]
Ok, a potential fix on crunchy-xml-decode has been made which match the solution I had in mind. I will try to do a fix tonight, hope it will work.

**Comment by Godzil** [comment]
Ok, I've made some changes on my local version that seem to works. I let it run to see, and will update later today with the changes it works.
It also detect if you have a premium account or not. I may at some point, make the software to refuse to work if you don't have one.

**Comment by Godzil** [comment]
Published v1.1.11 with changes on the login mechanism.
I'm closing this issue, but if you find any problem with login, please reopen it!

**Comment by Jfigs101** [comment]
I will test tonight and report back

**Comment by Godzil** [comment]
(At least the test that you are logged or not should be more reliable than it was before)
