### ISSUE TITLE
"You have a premium account! Good!"

### ISSUE THREAD

**Issue by UnattendedFlight** [Godzil/crunchyroll.js#8]
Whenever I try to download a series i get this message. ("You have a premium account! Good!")

I've for a long time used Deathspike's downloader until lately where it wont download certain series/episodes. 

So, i came over this and thought it seemed neat since you're using hsl rather than rtmp. But then i get this "error" :/

Suggestions?

**Comment by Godzil** [comment]
Are you in a non English country? If yes crunchy need some changes to support non English interface..

**Comment by UnattendedFlight** [comment]
Yeah, I live in Norway. But I'll set up my vpn in the meantime, to see if that works :)

Oh, and if you need any help setting up non English interfaces. Iiiii know a few scandinavian languages :)

**Comment by Godzil** [comment]
All possible help would be welcome for that!
I'm planning some changes to support different other languages. Probably for version 1.2 (see #1 )
